[package]
name = "bevy-transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { path = "../bevy" }
futures-intrusive = "0.4.0"
wgpu = "0.13"
pollster = "0.2.5"
crossbeam-channel = "0.5"
itertools = "0.10"

[[example]]
name = "generate"
